# Generated by Django 6.0.4 on 2026-04-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPatient', models.BigIntegerField()),
                ('idMedic', models.BigIntegerField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('state', models.CharField(default='PENDIENTE', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=50, unique=True)),
                ('speciality', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField(unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
